### ISSUE TITLE
Demo Link

### ISSUE THREAD

**Issue by seniorbee** [egegunes/hastatakip#1]
It'd be good to have a demo link to test the application

**Comment by egegunes** [comment]
This project is not meant to be a general patient tracking application. It's written to fit the client's needs specifically. Although it's open source, it is not a "open source project" and I have no intent to spend $$ to maintain a demo instance.

If you're interested to use it I can assist you to setup your own instance, so you can try it yourself.

**Comment by seniorbee** [comment]
Nope. I can set it up myself. I just didn't want to spend my time setting and running up a simple project.
